[package]
name = "linregress"
version = "0.1.0"
authors = ["Nils Mehrtens <nils@hasinila.de>"]
edition = "2018"

[dependencies]
failure = "~0.1.5"
hashbrown = "~0.1.8"
nalgebra = "~0.17.0"
statrs = "~0.10.0"

[dev-dependencies]
quickcheck = "~0.8.2"
quickcheck_macros = "~0.8.0"
special-fun = { git = "https://github.com/vks/special-fun" }

[features]
unstable = []
