[package]
name = "linregress"
version = "0.1.0"
authors = ["Nils Mehrtens <nils@hasinila.de>"]
edition = "2018"

[dependencies]
failure = "~0.1.5"
nalgebra = "~0.17.0"
libmath = "~0.2.1"
statrs = "~0.10.0"
